import type { ColonyPage } from "./types";
import { COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT, g, industry, s, term } from "./coi";

export const COI_PAGES_EXTRA: ColonyPage[] = [
  {
    tier: "guide",
    path: g("how-to-set-vendor-insurance-requirements"),
    slug: "how-to-set-vendor-insurance-requirements",
    title: "How to Set Vendor Insurance Requirements",
    primaryKeyword: "vendor insurance requirements",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-request-a-certificate-of-insurance"), s("coi-requirements-tracking")],
  },
  {
    tier: "guide",
    path: g("what-additional-insured-means-for-your-business"),
    slug: "what-additional-insured-means-for-your-business",
    title: "What Additional Insured Means for Your Business",
    primaryKeyword: "additional insured meaning",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, term("additional-insured")],
    linkSideways: [g("what-to-check-on-a-certificate-of-insurance"), s("additional-insured-certificate")],
  },
  {
    tier: "guide",
    path: g("how-to-build-a-coi-renewal-process"),
    slug: "how-to-build-a-coi-renewal-process",
    title: "How to Build a COI Renewal Process",
    primaryKeyword: "coi renewal process",
    difficulty: "hard",
    linkUp: [COI_HUB, COI_PRODUCT, COI_HEAD_SOLUTION],
    linkSideways: [g("how-to-track-coi-expirations"), s("coi-renewal-reminders")],
  },
  {
    tier: "guide",
    path: g("what-is-an-acord-25-form"),
    slug: "what-is-an-acord-25-form",
    title: "What Is an ACORD 25 Form?",
    primaryKeyword: "acord 25 form",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, term("acord-25")],
    linkSideways: [g("how-to-read-an-acord-25-certificate"), s("acord-25-tracking")],
  },
  {
    tier: "guide",
    path: g("how-to-verify-general-liability-on-a-coi"),
    slug: "how-to-verify-general-liability-on-a-coi",
    title: "How to Verify General Liability on a COI",
    primaryKeyword: "verify general liability coi",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, g("how-to-verify-coverage-limits-on-a-coi")],
    linkSideways: [g("what-to-check-on-a-certificate-of-insurance"), term("coverage-limit")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-cois-before-vendor-go-live"),
    slug: "how-to-collect-cois-before-vendor-go-live",
    title: "How to Collect COIs Before Vendor Go-Live",
    primaryKeyword: "collect coi before vendor go live",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT],
    linkSideways: [g("how-to-request-a-certificate-of-insurance"), s("vendor-insurance-certificate-tracking")],
  },
  {
    tier: "guide",
    path: g("how-to-audit-vendor-insurance-compliance"),
    slug: "how-to-audit-vendor-insurance-compliance",
    title: "How to Audit Vendor Insurance Compliance",
    primaryKeyword: "audit vendor insurance compliance",
    difficulty: "hard",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-build-a-coi-renewal-process"), s("coi-coverage-gap-alerts")],
  },
  {
    tier: "industry",
    path: industry("construction", "track-coi-expirations"),
    slug: "construction-track-coi-expirations",
    title: "Track COI Expirations for Construction",
    primaryKeyword: "construction coi tracking",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-collect-cois-from-subcontractors"), s("coi-subcontractor-monitoring")],
  },
  {
    tier: "industry",
    path: industry("healthcare", "track-coi-expirations"),
    slug: "healthcare-track-coi-expirations",
    title: "Track COI Expirations for Healthcare",
    primaryKeyword: "healthcare coi tracking",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), s("coi-expiration-alerts")],
  },
];
