import type { ColonyPage } from "./types";
import {
  COI_HEAD_SOLUTION,
  COI_HEAD_TOOL,
  COI_HUB,
  COI_PRODUCT,
  g,
  industry,
  s,
  term,
} from "./coi";

export const COI_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: COI_HEAD_SOLUTION,
    slug: "coi-tracking-software",
    title: "COI Tracking Software",
    primaryKeyword: "coi tracking software",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_PRODUCT],
    linkSideways: [s("certificate-of-insurance-tracker"), s("coi-expiration-alerts")],
  },
  {
    tier: "solution",
    path: s("coi-expiration-alerts"),
    slug: "coi-expiration-alerts",
    title: "COI Expiration Alerts",
    primaryKeyword: "coi expiration alerts",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("coi-expiration-alert-system"), g("how-to-track-coi-expirations")],
  },
  {
    tier: "solution",
    path: s("acord-25-tracking"),
    slug: "acord-25-tracking",
    title: "ACORD 25 Tracking",
    primaryKeyword: "acord 25 tracking",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("acord-25-tracking-tool"), g("how-to-read-an-acord-25-certificate")],
  },
  {
    tier: "solution",
    path: s("certificate-of-insurance-tracker"),
    slug: "certificate-of-insurance-tracker",
    title: "Certificate of Insurance Tracker",
    primaryKeyword: "certificate of insurance tracker",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("vendor-insurance-certificate-tracking"), g("how-to-track-coi-expirations")],
  },
  {
    tier: "solution",
    path: s("coi-renewal-reminders"),
    slug: "coi-renewal-reminders",
    title: "COI Renewal Reminders",
    primaryKeyword: "coi renewal reminders",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("coi-expiration-alerts"), g("how-to-set-coi-expiration-reminders")],
  },
  {
    tier: "solution",
    path: s("vendor-insurance-certificate-tracking"),
    slug: "vendor-insurance-certificate-tracking",
    title: "Vendor Insurance Certificate Tracking",
    primaryKeyword: "vendor insurance certificate tracking",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("certificate-of-insurance-tracker"), g("how-to-collect-cois-before-vendor-go-live")],
  },
  {
    tier: "solution",
    path: s("additional-insured-certificate"),
    slug: "additional-insured-certificate",
    title: "Additional Insured Certificate",
    primaryKeyword: "additional insured certificate",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("what-additional-insured-means-for-your-business"), term("additional-insured")],
  },
  {
    tier: "solution",
    path: s("coi-requirements-tracking"),
    slug: "coi-requirements-tracking",
    title: "COI Requirements Tracking",
    primaryKeyword: "coi requirements tracking",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-set-vendor-insurance-requirements"), s("coi-coverage-gap-alerts")],
  },
  {
    tier: "solution",
    path: s("coi-expiration-alert-system"),
    slug: "coi-expiration-alert-system",
    title: "COI Expiration Alert System",
    primaryKeyword: "coi expiration alert system",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [s("coi-expiration-alerts"), g("how-to-handle-an-expired-certificate-of-insurance")],
  },
  {
    tier: "solution",
    path: s("acord-25-tracking-tool"),
    slug: "acord-25-tracking-tool",
    title: "ACORD 25 Tracking Tool",
    primaryKeyword: "acord 25 tracking tool",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_HEAD_TOOL],
    linkSideways: [s("acord-25-tracking"), g("what-is-an-acord-25-form")],
  },
  {
    tier: "solution",
    path: s("coi-subcontractor-monitoring"),
    slug: "coi-subcontractor-monitoring",
    title: "COI Subcontractor Monitoring",
    primaryKeyword: "coi subcontractor monitoring",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-collect-cois-from-subcontractors"), industry("construction", "track-coi-expirations")],
  },
  {
    tier: "solution",
    path: s("coi-coverage-gap-alerts"),
    slug: "coi-coverage-gap-alerts",
    title: "COI Coverage Gap Alerts",
    primaryKeyword: "coi coverage gap alerts",
    difficulty: "hard",
    linkUp: [COI_HUB, COI_PRODUCT, COI_HEAD_SOLUTION],
    linkSideways: [g("how-to-audit-vendor-insurance-compliance"), s("coi-requirements-tracking")],
  },
];
