import type { ColonyLink, ColonyPage } from "./types";

export const COI_HUB = "/certificate-of-insurance/";
export const COI_PRODUCT = "/products/coi-tracker/";
export const COI_HEAD_SOLUTION = "/solutions/coi-tracking-software/";
export const COI_HEAD_TOOL = "/tools/acord-analyzer/";

export const s = (slug: string) => `/solutions/${slug}/`;
export const g = (slug: string) => `/guides/${slug}/`;
export const term = (slug: string) => `/glossary/${slug}/`;
export const industry = (industrySlug: string, workflowSlug: string) =>
  `/industries/${industrySlug}/${workflowSlug}/`;

export const COI_HUB_COLONY_GUIDES: ColonyLink[] = [
  { label: "How to track COI expirations", href: g("how-to-track-coi-expirations") },
  { label: "How to read an ACORD 25 certificate", href: g("how-to-read-an-acord-25-certificate") },
  { label: "What to check on a certificate of insurance", href: g("what-to-check-on-a-certificate-of-insurance") },
  { label: "How to request a certificate of insurance", href: g("how-to-request-a-certificate-of-insurance") },
  { label: "How to set COI expiration reminders", href: g("how-to-set-coi-expiration-reminders") },
  { label: "How to handle an expired certificate of insurance", href: g("how-to-handle-an-expired-certificate-of-insurance") },
  { label: "How to collect COIs from subcontractors", href: g("how-to-collect-cois-from-subcontractors") },
  { label: "How to verify coverage limits on a COI", href: g("how-to-verify-coverage-limits-on-a-coi") },
  { label: "What is an ACORD 25 form?", href: g("what-is-an-acord-25-form") },
];

export const COI_PAGES_BASE: ColonyPage[] = [
  {
    tier: "glossary",
    path: term("certificate-of-insurance"),
    slug: "certificate-of-insurance",
    title: "Certificate of Insurance",
    primaryKeyword: "certificate of insurance",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("what-to-check-on-a-certificate-of-insurance")],
    linkSideways: [term("acord-25"), term("coi-tracking")],
  },
  {
    tier: "glossary",
    path: term("acord-25"),
    slug: "acord-25",
    title: "ACORD 25",
    primaryKeyword: "acord 25",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("how-to-read-an-acord-25-certificate")],
    linkSideways: [term("certificate-of-insurance"), g("what-is-an-acord-25-form")],
  },
  {
    tier: "glossary",
    path: term("additional-insured"),
    slug: "additional-insured",
    title: "Additional Insured",
    primaryKeyword: "additional insured",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("what-additional-insured-means-for-your-business")],
    linkSideways: [term("certificate-holder"), s("additional-insured-certificate")],
  },
  {
    tier: "glossary",
    path: term("coverage-limit"),
    slug: "coverage-limit",
    title: "Coverage Limit",
    primaryKeyword: "coverage limit",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("how-to-verify-coverage-limits-on-a-coi")],
    linkSideways: [term("certificate-of-insurance"), g("how-to-verify-general-liability-on-a-coi")],
  },
  {
    tier: "glossary",
    path: term("coi-tracking"),
    slug: "coi-tracking",
    title: "COI Tracking",
    primaryKeyword: "coi tracking",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [term("certificate-of-insurance"), g("how-to-track-coi-expirations")],
  },
  {
    tier: "glossary",
    path: term("waiver-of-subrogation"),
    slug: "waiver-of-subrogation",
    title: "Waiver of Subrogation",
    primaryKeyword: "waiver of subrogation",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, g("what-to-check-on-a-certificate-of-insurance")],
    linkSideways: [term("additional-insured"), term("certificate-of-insurance")],
  },
  {
    tier: "glossary",
    path: term("certificate-holder"),
    slug: "certificate-holder",
    title: "Certificate Holder",
    primaryKeyword: "certificate holder",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("how-to-request-a-certificate-of-insurance")],
    linkSideways: [term("additional-insured"), term("certificate-of-insurance")],
  },
  {
    tier: "glossary",
    path: term("certificate-expiration-date"),
    slug: "certificate-expiration-date",
    title: "Certificate Expiration Date",
    primaryKeyword: "certificate expiration date",
    difficulty: "easy",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, g("how-to-track-coi-expirations")],
    linkSideways: [term("coi-tracking"), s("coi-expiration-alerts")],
  },
  {
    tier: "guide",
    path: g("how-to-track-coi-expirations"),
    slug: "how-to-track-coi-expirations",
    title: "How to Track COI Expirations",
    primaryKeyword: "track coi expirations",
    difficulty: "easy",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT],
    linkSideways: [g("how-to-set-coi-expiration-reminders"), g("how-to-handle-an-expired-certificate-of-insurance")],
  },
  {
    tier: "guide",
    path: g("how-to-read-an-acord-25-certificate"),
    slug: "how-to-read-an-acord-25-certificate",
    title: "How to Read an ACORD 25 Certificate",
    primaryKeyword: "read acord 25 certificate",
    difficulty: "easy",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, term("acord-25")],
    linkSideways: [g("what-to-check-on-a-certificate-of-insurance"), g("what-is-an-acord-25-form")],
  },
  {
    tier: "guide",
    path: g("what-to-check-on-a-certificate-of-insurance"),
    slug: "what-to-check-on-a-certificate-of-insurance",
    title: "What to Check on a Certificate of Insurance",
    primaryKeyword: "check certificate of insurance",
    difficulty: "easy",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, term("certificate-of-insurance")],
    linkSideways: [g("how-to-read-an-acord-25-certificate"), g("how-to-verify-coverage-limits-on-a-coi")],
  },
  {
    tier: "guide",
    path: g("how-to-request-a-certificate-of-insurance"),
    slug: "how-to-request-a-certificate-of-insurance",
    title: "How to Request a Certificate of Insurance",
    primaryKeyword: "request certificate of insurance",
    difficulty: "easy",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT],
    linkSideways: [g("how-to-collect-cois-from-subcontractors"), g("how-to-collect-cois-before-vendor-go-live")],
  },
  {
    tier: "guide",
    path: g("how-to-set-coi-expiration-reminders"),
    slug: "how-to-set-coi-expiration-reminders",
    title: "How to Set COI Expiration Reminders",
    primaryKeyword: "coi expiration reminders",
    difficulty: "easy",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), s("coi-renewal-reminders")],
  },
  {
    tier: "guide",
    path: g("how-to-handle-an-expired-certificate-of-insurance"),
    slug: "how-to-handle-an-expired-certificate-of-insurance",
    title: "How to Handle an Expired Certificate of Insurance",
    primaryKeyword: "expired certificate of insurance",
    difficulty: "medium",
    linkUp: [COI_HUB, COI_HEAD_SOLUTION, COI_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), s("coi-expiration-alerts")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-cois-from-subcontractors"),
    slug: "how-to-collect-cois-from-subcontractors",
    title: "How to Collect COIs from Subcontractors",
    primaryKeyword: "collect cois from subcontractors",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, COI_PRODUCT],
    linkSideways: [g("how-to-request-a-certificate-of-insurance"), s("coi-subcontractor-monitoring")],
  },
  {
    tier: "guide",
    path: g("how-to-verify-coverage-limits-on-a-coi"),
    slug: "how-to-verify-coverage-limits-on-a-coi",
    title: "How to Verify Coverage Limits on a COI",
    primaryKeyword: "verify coverage limits coi",
    difficulty: "medium",
    linkUp: [COI_HEAD_SOLUTION, COI_HUB, term("coverage-limit")],
    linkSideways: [g("what-to-check-on-a-certificate-of-insurance"), g("how-to-verify-general-liability-on-a-coi")],
  },
];
