import type { ColonyPage } from "./types";
import { COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_HUB, COMPLIANCE_PRODUCT, g, industry, s, term } from "./compliance";

export const COMPLIANCE_PAGES_EXTRA: ColonyPage[] = [
  {
    tier: "guide",
    path: g("how-to-audit-vendor-onboarding-records"),
    slug: "how-to-audit-vendor-onboarding-records",
    title: "How to Audit Vendor Onboarding Records",
    primaryKeyword: "audit vendor onboarding records",
    difficulty: "hard",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, term("audit-evidence")],
    linkSideways: [g("how-to-export-vendor-onboarding-evidence"), g("vendor-compliance-checklist")],
  },
  {
    tier: "guide",
    path: g("how-to-block-payments-for-non-compliant-vendors"),
    slug: "how-to-block-payments-for-non-compliant-vendors",
    title: "How to Block Payments for Non-Compliant Vendors",
    primaryKeyword: "block payments non compliant vendors",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_PRODUCT, COMPLIANCE_HEAD_SOLUTION],
    linkSideways: [g("how-to-collect-w9s-from-vendors"), s("vendor-payment-hold-controls")],
  },
  {
    tier: "guide",
    path: g("how-to-onboard-high-risk-vendors"),
    slug: "how-to-onboard-high-risk-vendors",
    title: "How to Onboard High-Risk Vendors",
    primaryKeyword: "high risk vendor onboarding",
    difficulty: "hard",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, term("due-diligence")],
    linkSideways: [g("how-to-screen-vendors-against-the-oig-list"), s("vendor-due-diligence-software")],
  },
  {
    tier: "guide",
    path: g("how-to-set-vendor-document-requirements-by-tier"),
    slug: "how-to-set-vendor-document-requirements-by-tier",
    title: "How to Set Vendor Document Requirements by Tier",
    primaryKeyword: "vendor document requirements by tier",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, term("compliance-control")],
    linkSideways: [g("how-to-onboard-high-risk-vendors"), s("vendor-risk-tiering-software")],
  },
  {
    tier: "guide",
    path: g("how-to-handle-incomplete-vendor-packets"),
    slug: "how-to-handle-incomplete-vendor-packets",
    title: "How to Handle Incomplete Vendor Packets",
    primaryKeyword: "incomplete vendor packet",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_HUB, g("vendor-compliance-checklist")],
    linkSideways: [g("how-to-block-payments-for-non-compliant-vendors"), s("vendor-packet-software")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-w9-and-coi-together"),
    slug: "how-to-collect-w9-and-coi-together",
    title: "How to Collect W-9 and COI Together",
    primaryKeyword: "collect w9 and coi together",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_HUB, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-collect-w9s-from-vendors"), g("how-to-track-coi-expirations")],
  },
  {
    tier: "guide",
    path: g("how-to-track-vendor-onboarding-status"),
    slug: "how-to-track-vendor-onboarding-status",
    title: "How to Track Vendor Onboarding Status",
    primaryKeyword: "vendor onboarding status",
    difficulty: "easy",
    linkUp: [COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_HUB, COMPLIANCE_PRODUCT],
    linkSideways: [g("vendor-compliance-checklist"), s("vendor-compliance-dashboard")],
  },
  {
    tier: "industry",
    path: industry("healthcare", "screen-vendors-against-exclusion-lists"),
    slug: "healthcare-screen-vendors-against-exclusion-lists",
    title: "Screen Vendors Against Exclusion Lists for Healthcare",
    primaryKeyword: "healthcare vendor compliance",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-screen-vendors-against-the-oig-list"), s("oig-exclusion-check")],
  },
  {
    tier: "industry",
    path: industry("multi-site-retail", "build-vendor-onboarding-packets"),
    slug: "multi-site-retail-build-vendor-onboarding-packets",
    title: "Build Vendor Onboarding Packets for Multi-site Retail",
    primaryKeyword: "multi-site retail vendor compliance",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), g("vendor-compliance-checklist")],
  },
];
