import type { ColonyPage } from "./types";
import {
  COMPLIANCE_HEAD_SOLUTION,
  COMPLIANCE_HEAD_TOOL,
  COMPLIANCE_HUB,
  COMPLIANCE_PRODUCT,
  g,
  s,
  term,
} from "./compliance";

export const COMPLIANCE_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: COMPLIANCE_HEAD_SOLUTION,
    slug: "third-party-vendor-compliance",
    title: "Third-Party Vendor Compliance",
    primaryKeyword: "third party vendor compliance",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_PRODUCT],
    linkSideways: [s("vendor-compliance-dashboard"), g("vendor-compliance-checklist")],
  },
  {
    tier: "solution",
    path: s("vendor-due-diligence-software"),
    slug: "vendor-due-diligence-software",
    title: "Vendor Due Diligence Software",
    primaryKeyword: "vendor due diligence software",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-onboard-high-risk-vendors"), term("due-diligence")],
  },
  {
    tier: "solution",
    path: s("vendor-compliance-dashboard"),
    slug: "vendor-compliance-dashboard",
    title: "Vendor Compliance Dashboard",
    primaryKeyword: "vendor compliance dashboard",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), s("third-party-vendor-compliance")],
  },
  {
    tier: "solution",
    path: s("vendor-packet-software"),
    slug: "vendor-packet-software",
    title: "Vendor Packet Software",
    primaryKeyword: "vendor packet software",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [s("vendor-onboarding-checklist"), g("how-to-build-a-vendor-onboarding-checklist")],
  },
  {
    tier: "solution",
    path: s("w9-collection-software"),
    slug: "w9-collection-software",
    title: "W-9 Collection Software",
    primaryKeyword: "w9 collection software",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-collect-w9s-from-vendors"), term("w-9")],
  },
  {
    tier: "solution",
    path: s("coi-tracking-software"),
    slug: "coi-tracking-software",
    title: "COI Tracking Software",
    primaryKeyword: "coi tracking software",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), term("certificate-of-insurance")],
  },
  {
    tier: "solution",
    path: s("oig-exclusion-check"),
    slug: "oig-exclusion-check",
    title: "OIG Exclusion Check",
    primaryKeyword: "oig exclusion check",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-screen-vendors-against-the-oig-list"), term("oig-exclusion")],
  },
  {
    tier: "solution",
    path: s("vendor-payment-hold-controls"),
    slug: "vendor-payment-hold-controls",
    title: "Vendor Payment Hold Controls",
    primaryKeyword: "vendor payment hold controls",
    difficulty: "hard",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_PRODUCT, COMPLIANCE_HEAD_SOLUTION],
    linkSideways: [g("how-to-block-payments-for-non-compliant-vendors"), s("vendor-compliance-dashboard")],
  },
  {
    tier: "solution",
    path: s("vendor-risk-tiering-software"),
    slug: "vendor-risk-tiering-software",
    title: "Vendor Risk Tiering Software",
    primaryKeyword: "vendor risk tiering software",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-set-vendor-document-requirements-by-tier"), s("vendor-due-diligence-software")],
  },
  {
    tier: "solution",
    path: s("vendor-onboarding-checklist"),
    slug: "vendor-onboarding-checklist",
    title: "Vendor Onboarding Checklist",
    primaryKeyword: "vendor onboarding checklist",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("vendor-packet-software")],
  },
  {
    tier: "solution",
    path: s("w9-validation-before-payment"),
    slug: "w9-validation-before-payment",
    title: "W-9 Validation Before Payment",
    primaryKeyword: "w9 validation before payment",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-block-payments-for-non-compliant-vendors"), s("w9-collection-software")],
  },
  {
    tier: "solution",
    path: s("coi-expiration-alerts"),
    slug: "coi-expiration-alerts",
    title: "COI Expiration Alerts",
    primaryKeyword: "coi expiration alerts",
    difficulty: "medium",
    linkUp: [COMPLIANCE_HUB, COMPLIANCE_HEAD_SOLUTION, COMPLIANCE_PRODUCT],
    linkSideways: [g("how-to-track-coi-expirations"), s("coi-tracking-software")],
  },
];
