import type { ColonyPage } from "./types";
import {
  CONTRACT_HEAD_SOLUTION,
  CONTRACT_HEAD_TOOL,
  CONTRACT_HUB,
  CONTRACT_PRODUCT,
  g,
  s,
  term,
} from "./contract";

export const CONTRACT_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: CONTRACT_HEAD_SOLUTION,
    slug: "contract-renewal-tracking",
    title: "Contract Renewal Tracking",
    primaryKeyword: "contract renewal tracking",
    difficulty: "hard",
    linkUp: [CONTRACT_PRODUCT, CONTRACT_HEAD_TOOL],
    linkSideways: [s("contract-expiration-alerts"), s("contract-notice-period-tracking")],
  },
  {
    tier: "solution",
    path: s("contract-expiration-alerts"),
    slug: "contract-expiration-alerts",
    title: "Contract Expiration Alerts",
    primaryKeyword: "contract expiration alerts",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-renewal-tracking"), s("contract-notice-period-tracking")],
  },
  {
    tier: "solution",
    path: s("contract-notice-period-tracking"),
    slug: "contract-notice-period-tracking",
    title: "Contract Notice Period Tracking",
    primaryKeyword: "contract notice period tracking",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-notice-period-tracker"), g("how-to-find-a-contract-notice-period")],
  },
  {
    tier: "solution",
    path: s("vendor-contract-management"),
    slug: "vendor-contract-management",
    title: "Vendor Contract Management",
    primaryKeyword: "vendor contract management",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-msa-sow-linking"), s("contract-renewal-tracking")],
  },
  {
    tier: "solution",
    path: s("contract-risk-review-software"),
    slug: "contract-risk-review-software",
    title: "Contract Risk Review Software",
    primaryKeyword: "contract risk review software",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-review-checklist"), s("vendor-contract-management")],
  },
  {
    tier: "solution",
    path: s("contract-review-checklist"),
    slug: "contract-review-checklist",
    title: "Contract Review Checklist",
    primaryKeyword: "contract review checklist",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, s("contract-risk-review-software")],
    linkSideways: [s("contract-notice-period-tracking"), term("termination-clause")],
  },
  {
    tier: "solution",
    path: s("contract-notice-period-tracker"),
    slug: "contract-notice-period-tracker",
    title: "Contract Notice Period Tracker",
    primaryKeyword: "contract notice period tracker",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-notice-period-tracking"), s("contract-auto-renewal-prevention")],
  },
  {
    tier: "solution",
    path: s("contract-saas-renewal-management"),
    slug: "contract-saas-renewal-management",
    title: "Contract SaaS Renewal Management",
    primaryKeyword: "saas contract renewal management",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-track-saas-contract-renewals"), s("contract-auto-renewal-prevention")],
  },
  {
    tier: "solution",
    path: s("contract-obligation-tracking"),
    slug: "contract-obligation-tracking",
    title: "Contract Obligation Tracking",
    primaryKeyword: "contract obligation tracking",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [s("contract-msa-sow-linking"), s("vendor-contract-management")],
  },
  {
    tier: "solution",
    path: s("contract-msa-sow-linking"),
    slug: "contract-msa-sow-linking",
    title: "Contract MSA SOW Linking",
    primaryKeyword: "msa sow linking",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, s("vendor-contract-management")],
    linkSideways: [term("statement-of-work"), g("how-to-link-contracts-to-vendor-records")],
  },
  {
    tier: "solution",
    path: s("contract-auto-renewal-prevention"),
    slug: "contract-auto-renewal-prevention",
    title: "Contract Auto-Renewal Prevention",
    primaryKeyword: "contract auto-renewal prevention",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_PRODUCT, CONTRACT_HEAD_SOLUTION],
    linkSideways: [g("how-to-avoid-accidental-auto-renewals"), s("contract-notice-period-tracker")],
  },
];
