import type { ColonyPage } from "./types";
import {
  CONTRACT_HEAD_SOLUTION,
  CONTRACT_HUB,
  CONTRACT_PRODUCT,
  g,
  industry,
  s,
  term,
} from "./contract";

export const CONTRACT_PAGES_EXTRA: ColonyPage[] = [
  {
    tier: "guide",
    path: g("how-to-maintain-a-contract-renewal-calendar"),
    slug: "how-to-maintain-a-contract-renewal-calendar",
    title: "How to Maintain a Contract Renewal Calendar",
    primaryKeyword: "maintain contract renewal calendar",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, g("how-to-build-a-contract-renewal-calendar")],
    linkSideways: [g("how-to-avoid-missing-contract-renewal-deadlines"), g("how-to-track-contract-renewals")],
  },
  {
    tier: "guide",
    path: g("how-to-track-saas-contract-renewals"),
    slug: "how-to-track-saas-contract-renewals",
    title: "How to Track SaaS Contract Renewals",
    primaryKeyword: "track saas contract renewals",
    difficulty: "medium",
    linkUp: [CONTRACT_HEAD_SOLUTION, CONTRACT_HUB, s("contract-saas-renewal-management")],
    linkSideways: [g("how-to-avoid-accidental-auto-renewals"), g("how-to-track-contract-renewals")],
  },
  {
    tier: "guide",
    path: g("how-to-monitor-notice-periods-for-vendors"),
    slug: "how-to-monitor-notice-periods-for-vendors",
    title: "How to Monitor Notice Periods for Vendors",
    primaryKeyword: "monitor vendor notice periods",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, s("contract-notice-period-tracker")],
    linkSideways: [g("how-to-find-a-contract-notice-period"), g("how-to-track-notice-periods-across-a-portfolio")],
  },
  {
    tier: "guide",
    path: g("how-to-avoid-missing-contract-renewal-deadlines"),
    slug: "how-to-avoid-missing-contract-renewal-deadlines",
    title: "How to Avoid Missing Contract Renewal Deadlines",
    primaryKeyword: "avoid missing contract renewal deadlines",
    difficulty: "medium",
    linkUp: [CONTRACT_HEAD_SOLUTION, CONTRACT_HUB, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-maintain-a-contract-renewal-calendar"), s("contract-expiration-alerts")],
  },
  {
    tier: "guide",
    path: g("how-to-give-notice-of-non-renewal"),
    slug: "how-to-give-notice-of-non-renewal",
    title: "How to Give Notice of Non-Renewal",
    primaryKeyword: "give notice of non-renewal",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, g("how-to-find-a-contract-notice-period")],
    linkSideways: [g("how-to-avoid-accidental-auto-renewals"), term("termination-clause")],
  },
  {
    tier: "guide",
    path: g("how-to-prepare-for-a-contract-renegotiation"),
    slug: "how-to-prepare-for-a-contract-renegotiation",
    title: "How to Prepare for a Contract Renegotiation",
    primaryKeyword: "prepare for contract renegotiation",
    difficulty: "medium",
    linkUp: [CONTRACT_HEAD_SOLUTION, CONTRACT_HUB, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-negotiate-before-auto-renewal"), g("how-to-renew-a-vendor-contract")],
  },
  {
    tier: "guide",
    path: g("how-to-document-contract-renewal-decisions"),
    slug: "how-to-document-contract-renewal-decisions",
    title: "How to Document Contract Renewal Decisions",
    primaryKeyword: "document contract renewal decisions",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-track-contract-renewals"), g("how-to-renew-a-vendor-contract")],
  },
  {
    tier: "guide",
    path: g("how-to-renew-a-vendor-contract"),
    slug: "how-to-renew-a-vendor-contract",
    title: "How to Renew a Vendor Contract",
    primaryKeyword: "renew vendor contract",
    difficulty: "medium",
    linkUp: [CONTRACT_HEAD_SOLUTION, CONTRACT_HUB, s("vendor-contract-management")],
    linkSideways: [g("how-to-document-contract-renewal-decisions"), g("how-to-prepare-for-a-contract-renegotiation")],
  },
  {
    tier: "guide",
    path: g("how-to-negotiate-before-auto-renewal"),
    slug: "how-to-negotiate-before-auto-renewal",
    title: "How to Negotiate Before Auto-Renewal",
    primaryKeyword: "negotiate before auto-renewal",
    difficulty: "hard",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, s("contract-auto-renewal-prevention")],
    linkSideways: [g("how-to-avoid-accidental-auto-renewals"), g("how-to-prepare-for-a-contract-renegotiation")],
  },
  {
    tier: "guide",
    path: g("how-to-link-contracts-to-vendor-records"),
    slug: "how-to-link-contracts-to-vendor-records",
    title: "How to Link Contracts to Vendor Records",
    primaryKeyword: "link contracts to vendor records",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_PRODUCT, s("vendor-contract-management")],
    linkSideways: [g("how-to-track-contract-renewals"), s("contract-msa-sow-linking")],
  },
  {
    tier: "industry",
    path: industry("logistics", "monitor-contract-renewals"),
    slug: "logistics-monitor-contract-renewals",
    title: "Monitor Contract Renewals for Logistics",
    primaryKeyword: "logistics contract renewals",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-track-contract-renewals"), g("how-to-avoid-accidental-auto-renewals")],
  },
  {
    tier: "industry",
    path: industry("manufacturing", "monitor-contract-renewals"),
    slug: "manufacturing-monitor-contract-renewals",
    title: "Monitor Contract Renewals for Manufacturing",
    primaryKeyword: "manufacturing contract renewals",
    difficulty: "medium",
    linkUp: [CONTRACT_HUB, CONTRACT_HEAD_SOLUTION, CONTRACT_PRODUCT],
    linkSideways: [g("how-to-track-contract-renewals"), g("how-to-track-notice-periods-across-a-portfolio")],
  },
];
