import type { ColonyDefinition, ColonyLink, ColonyPage } from "./types";

export const OIG_HUB = "/exclusion-monitoring/";
export const OIG_PRODUCT = "/products/exclusion-monitor/";
export const OIG_HEAD_SOLUTION = "/solutions/oig-exclusion-check/";
export const OIG_HEAD_TOOL = "/tools/oig-search/";
const s = (slug: string) => `/solutions/${slug}/`;
const g = (slug: string) => `/guides/${slug}/`;
const term = (slug: string) => `/glossary/${slug}/`;

export const OIG_HUB_COLONY_GUIDES: ColonyLink[] = [
  { label: "How to search the OIG LEIE database", href: g("how-to-search-the-oig-leie-database") },
  { label: "What is the OIG LEIE list?", href: g("what-is-the-oig-leie-list") },
  { label: "How to screen vendors against the OIG list", href: g("how-to-screen-vendors-against-the-oig-list") },
  { label: "How often should healthcare providers screen OIG?", href: g("how-often-should-healthcare-providers-screen-oig") },
  { label: "How to screen billing vendors for OIG exclusions", href: g("how-to-screen-billing-vendors-for-oig-exclusions") },
  { label: "How to document exclusion screening", href: g("how-to-document-exclusion-screening") },
  { label: "How to prepare for a CMS exclusion screening audit", href: g("how-to-prepare-for-a-cms-exclusion-screening-audit") },
  { label: "OIG and OFAC: what healthcare providers must screen", href: g("oig-sam-and-ofac-what-healthcare-providers-must-screen") },
  { label: "How to schedule monthly OIG screening", href: g("how-to-schedule-monthly-oig-screening") },
];

export const OIG_PAGES_BASE: ColonyPage[] = [
  {
    tier: "glossary",
    path: term("oig-exclusion"),
    slug: "oig-exclusion",
    title: "OIG Exclusion",
    primaryKeyword: "oig exclusion",
    difficulty: "easy",
    linkUp: [OIG_HUB, OIG_HEAD_SOLUTION, term("leie")],
    linkSideways: [term("exclusion-screening"), g("what-is-the-oig-leie-list")],
  },
  {
    tier: "glossary",
    path: term("leie"),
    slug: "leie",
    title: "LEIE",
    primaryKeyword: "leie list",
    difficulty: "easy",
    linkUp: [OIG_HUB, g("what-is-the-oig-leie-list"), OIG_HEAD_SOLUTION],
    linkSideways: [term("oig-exclusion"), g("how-to-search-the-oig-leie-database")],
  },
  {
    tier: "glossary",
    path: term("exclusion-screening"),
    slug: "exclusion-screening",
    title: "Exclusion Screening",
    primaryKeyword: "exclusion screening",
    difficulty: "easy",
    linkUp: [OIG_HUB, OIG_HEAD_SOLUTION, OIG_PRODUCT],
    linkSideways: [term("leie"), g("how-to-screen-vendors-against-the-oig-list")],
  },
  {
    tier: "glossary",
    path: term("re-screening-cadence"),
    slug: "re-screening-cadence",
    title: "Re-screening Cadence",
    primaryKeyword: "oig re-screening frequency",
    difficulty: "easy",
    linkUp: [OIG_HUB, g("how-often-should-healthcare-providers-screen-oig"), OIG_HEAD_SOLUTION],
    linkSideways: [term("exclusion-screening"), g("how-to-schedule-monthly-oig-screening")],
  },
  {
    tier: "glossary",
    path: term("exclusion-match-review"),
    slug: "exclusion-match-review",
    title: "Exclusion Match Review",
    primaryKeyword: "oig match review",
    difficulty: "medium",
    linkUp: [OIG_HEAD_SOLUTION, OIG_HUB, g("how-to-resolve-an-oig-list-match")],
    linkSideways: [term("false-positive-match"), g("what-to-do-when-oig-screening-finds-a-match")],
  },
  {
    tier: "glossary",
    path: term("false-positive-match"),
    slug: "false-positive-match",
    title: "False Positive Match",
    primaryKeyword: "oig false positive",
    difficulty: "medium",
    linkUp: [OIG_HEAD_SOLUTION, g("how-to-resolve-an-oig-list-match"), OIG_HUB],
    linkSideways: [term("exclusion-match-review"), g("what-to-do-when-oig-screening-finds-a-match")],
  },
  {
    tier: "guide",
    path: g("how-to-search-the-oig-leie-database"),
    slug: "how-to-search-the-oig-leie-database",
    title: "How to Search the OIG LEIE Database",
    primaryKeyword: "oig leie database search",
    difficulty: "easy",
    linkUp: [OIG_HEAD_SOLUTION, OIG_HUB, OIG_PRODUCT],
    linkSideways: [g("what-is-the-oig-leie-list"), g("how-to-screen-vendors-against-the-oig-list")],
  },
  {
    tier: "guide",
    path: g("what-is-the-oig-leie-list"),
    slug: "what-is-the-oig-leie-list",
    title: "What Is the OIG LEIE List?",
    primaryKeyword: "oig leie list",
    difficulty: "easy",
    linkUp: [OIG_HUB, OIG_HEAD_SOLUTION, term("oig-exclusion")],
    linkSideways: [g("how-to-search-the-oig-leie-database"), g("how-to-screen-vendors-against-the-oig-list")],
  },
  {
    tier: "guide",
    path: g("how-to-screen-vendors-against-the-oig-list"),
    slug: "how-to-screen-vendors-against-the-oig-list",
    title: "How to Screen Vendors Against the OIG List",
    primaryKeyword: "screen vendors oig list",
    difficulty: "medium",
    linkUp: [OIG_HEAD_SOLUTION, OIG_HUB, OIG_PRODUCT],
    linkSideways: [g("how-to-search-the-oig-leie-database"), g("how-to-document-exclusion-screening")],
  },
  {
    tier: "guide",
    path: g("how-to-screen-billing-vendors-for-oig-exclusions"),
    slug: "how-to-screen-billing-vendors-for-oig-exclusions",
    title: "How to Screen Billing Vendors for OIG Exclusions",
    primaryKeyword: "screen billing vendors oig",
    difficulty: "medium",
    linkUp: [OIG_HEAD_SOLUTION, OIG_HUB, OIG_PRODUCT],
    linkSideways: [g("how-to-screen-vendors-against-the-oig-list"), g("how-often-should-healthcare-providers-screen-oig")],
  },
  {
    tier: "guide",
    path: g("how-often-should-healthcare-providers-screen-oig"),
    slug: "how-often-should-healthcare-providers-screen-oig",
    title: "How Often Should Healthcare Providers Screen OIG?",
    primaryKeyword: "how often screen oig",
    difficulty: "medium",
    linkUp: [OIG_HUB, OIG_HEAD_SOLUTION, OIG_PRODUCT],
    linkSideways: [g("how-to-schedule-monthly-oig-screening"), g("how-often-to-re-screen-for-exclusions")],
  },
  {
    tier: "guide",
    path: g("how-to-schedule-monthly-oig-screening"),
    slug: "how-to-schedule-monthly-oig-screening",
    title: "How to Schedule Monthly OIG Screening",
    primaryKeyword: "monthly oig screening",
    difficulty: "medium",
    linkUp: [OIG_HUB, OIG_HEAD_SOLUTION, OIG_PRODUCT],
    linkSideways: [g("how-often-should-healthcare-providers-screen-oig"), s("monthly-oig-screening")],
  },
  {
    tier: "guide",
    path: g("how-to-document-exclusion-screening"),
    slug: "how-to-document-exclusion-screening",
    title: "How to Document Exclusion Screening",
    primaryKeyword: "document oig screening",
    difficulty: "medium",
    linkUp: [OIG_HEAD_SOLUTION, OIG_HUB, OIG_PRODUCT],
    linkSideways: [g("how-to-export-oig-screening-evidence-for-auditors"), g("how-to-screen-vendors-against-the-oig-list")],
  },
  {
    tier: "guide",
    path: g("how-to-prepare-for-a-cms-exclusion-screening-audit"),
    slug: "how-to-prepare-for-a-cms-exclusion-screening-audit",
    title: "How to Prepare for a CMS Exclusion Screening Audit",
    primaryKeyword: "cms exclusion screening audit",
    difficulty: "hard",
    linkUp: [OIG_HUB, OIG_PRODUCT, OIG_HEAD_SOLUTION],
    linkSideways: [g("how-to-export-oig-screening-evidence-for-auditors"), g("how-to-document-exclusion-screening")],
  },
];