import type { ColonyPage } from "./types";
import {
  PORTAL_HEAD_SOLUTION,
  PORTAL_HEAD_TOOL,
  PORTAL_HUB,
  PORTAL_PRODUCT,
  g,
  s,
  term,
} from "./portal";

export const PORTAL_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: PORTAL_HEAD_SOLUTION,
    slug: "vendor-setup-portal",
    title: "Vendor Setup Portal",
    primaryKeyword: "vendor setup portal",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_PRODUCT],
    linkSideways: [s("vendor-document-portal"), s("vendor-document-collection")],
  },
  {
    tier: "solution",
    path: s("vendor-document-collection"),
    slug: "vendor-document-collection",
    title: "Vendor Document Collection",
    primaryKeyword: "vendor document collection",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [s("vendor-document-portal"), g("how-to-collect-vendor-documents-in-one-place")],
  },
  {
    tier: "solution",
    path: s("vendor-packet-software"),
    slug: "vendor-packet-software",
    title: "Vendor Packet Software",
    primaryKeyword: "vendor packet software",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [s("vendor-onboarding-checklist"), s("vendor-setup-portal")],
  },
  {
    tier: "solution",
    path: s("vendor-document-portal"),
    slug: "vendor-document-portal",
    title: "Vendor Document Portal",
    primaryKeyword: "vendor document portal",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [s("vendor-setup-portal"), g("how-to-send-a-vendor-portal-link")],
  },
  {
    tier: "solution",
    path: s("vendor-information-management"),
    slug: "vendor-information-management",
    title: "Vendor Information Management",
    primaryKeyword: "vendor information management",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [term("vendor-master-record"), PORTAL_HEAD_TOOL],
  },
  {
    tier: "solution",
    path: s("supplier-onboarding-workflow"),
    slug: "supplier-onboarding-workflow",
    title: "Supplier Onboarding Workflow",
    primaryKeyword: "supplier onboarding workflow",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [s("vendor-onboarding-checklist"), g("how-to-track-vendor-onboarding-status")],
  },
  {
    tier: "solution",
    path: s("vendor-onboarding-checklist"),
    slug: "vendor-onboarding-checklist",
    title: "Vendor Onboarding Checklist",
    primaryKeyword: "vendor onboarding checklist",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("supplier-onboarding-workflow")],
  },
  {
    tier: "solution",
    path: s("third-party-vendor-compliance"),
    slug: "third-party-vendor-compliance",
    title: "Third-Party Vendor Compliance",
    primaryKeyword: "third party vendor compliance",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("vendor-compliance-checklist"), s("vendor-compliance-dashboard")],
  },
  {
    tier: "solution",
    path: s("vendor-compliance-dashboard"),
    slug: "vendor-compliance-dashboard",
    title: "Vendor Compliance Dashboard",
    primaryKeyword: "vendor compliance dashboard",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), s("third-party-vendor-compliance")],
  },
  {
    tier: "solution",
    path: s("vendor-due-diligence-software"),
    slug: "vendor-due-diligence-software",
    title: "Vendor Due Diligence Software",
    primaryKeyword: "vendor due diligence software",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-collect-vendor-questionnaires"), s("third-party-vendor-compliance")],
  },
];
