import type { ColonyPage } from "./types";
import { PORTAL_HEAD_SOLUTION, PORTAL_HUB, PORTAL_PRODUCT, g, industry, s, term } from "./portal";

export const PORTAL_PAGES_EXTRA: ColonyPage[] = [
  {
    tier: "guide",
    path: g("how-to-approve-a-new-vendor"),
    slug: "how-to-approve-a-new-vendor",
    title: "How to Approve a New Vendor",
    primaryKeyword: "new vendor approval",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), g("how-to-handle-incomplete-vendor-packets")],
  },
  {
    tier: "guide",
    path: g("how-to-reduce-vendor-onboarding-time"),
    slug: "how-to-reduce-vendor-onboarding-time",
    title: "How to Reduce Vendor Onboarding Time",
    primaryKeyword: "reduce vendor onboarding time",
    difficulty: "medium",
    linkUp: [PORTAL_HEAD_SOLUTION, PORTAL_HUB, PORTAL_PRODUCT],
    linkSideways: [g("how-to-send-a-vendor-portal-link"), s("supplier-onboarding-workflow")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-vendor-questionnaires"),
    slug: "how-to-collect-vendor-questionnaires",
    title: "How to Collect Vendor Questionnaires",
    primaryKeyword: "collect vendor questionnaires",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-collect-vendor-documents-in-one-place"), s("vendor-document-collection")],
  },
  {
    tier: "guide",
    path: g("how-to-assign-vendor-onboarding-owners"),
    slug: "how-to-assign-vendor-onboarding-owners",
    title: "How to Assign Vendor Onboarding Owners",
    primaryKeyword: "vendor onboarding owners",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), s("supplier-onboarding-workflow")],
  },
  {
    tier: "guide",
    path: g("how-to-set-vendor-document-requirements-by-tier"),
    slug: "how-to-set-vendor-document-requirements-by-tier",
    title: "How to Set Vendor Document Requirements by Tier",
    primaryKeyword: "vendor document requirements by tier",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, term("vendor-packet")],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("vendor-onboarding-checklist")],
  },
  {
    tier: "guide",
    path: g("how-to-handle-vendor-name-changes-at-onboarding"),
    slug: "how-to-handle-vendor-name-changes-at-onboarding",
    title: "How to Handle Vendor Name Changes at Onboarding",
    primaryKeyword: "vendor name changes onboarding",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, term("vendor-master-record")],
    linkSideways: [g("how-to-collect-vendor-documents-in-one-place"), s("vendor-information-management")],
  },
  {
    tier: "industry",
    path: industry("construction", "build-vendor-onboarding-packets"),
    slug: "construction-build-vendor-onboarding-packets",
    title: "Build Vendor Onboarding Packets for Construction",
    primaryKeyword: "construction vendor portal",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-collect-w9-and-coi-together"), g("how-to-send-a-vendor-portal-link")],
  },
  {
    tier: "industry",
    path: industry("facilities-services", "build-vendor-onboarding-packets"),
    slug: "facilities-services-build-vendor-onboarding-packets",
    title: "Build Vendor Onboarding Packets for Facilities Services",
    primaryKeyword: "facilities vendor portal",
    difficulty: "medium",
    linkUp: [PORTAL_HUB, PORTAL_HEAD_SOLUTION, PORTAL_PRODUCT],
    linkSideways: [g("how-to-standardize-vendor-setup-across-locations"), s("vendor-document-portal")],
  },
];
