import type { ColonyPage } from "./types";
import {
  VENDOR_HEAD_SOLUTION,
  VENDOR_HEAD_TOOL,
  VENDOR_HUB,
  VENDOR_PRODUCT,
  g,
  s,
  term,
} from "./vendor";

export const VENDOR_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: VENDOR_HEAD_SOLUTION,
    slug: "vendor-packet-software",
    title: "Vendor Packet Software",
    primaryKeyword: "vendor packet software",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [s("vendor-onboarding-checklist"), s("vendor-setup-portal")],
  },
  {
    tier: "solution",
    path: s("vendor-onboarding-checklist"),
    slug: "vendor-onboarding-checklist",
    title: "Vendor Onboarding Checklist",
    primaryKeyword: "vendor onboarding checklist",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("supplier-onboarding-workflow")],
  },
  {
    tier: "solution",
    path: s("supplier-onboarding-workflow"),
    slug: "supplier-onboarding-workflow",
    title: "Supplier Onboarding Workflow",
    primaryKeyword: "supplier onboarding workflow",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [s("vendor-onboarding-checklist"), g("how-to-track-vendor-onboarding-status")],
  },
  {
    tier: "solution",
    path: s("vendor-document-collection"),
    slug: "vendor-document-collection",
    title: "Vendor Document Collection",
    primaryKeyword: "vendor document collection",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [s("vendor-document-portal"), g("how-to-collect-vendor-documents-in-one-place")],
  },
  {
    tier: "solution",
    path: s("vendor-setup-portal"),
    slug: "vendor-setup-portal",
    title: "Vendor Setup Portal",
    primaryKeyword: "vendor setup portal",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-send-a-vendor-portal-link"), s("vendor-document-portal")],
  },
  {
    tier: "solution",
    path: s("vendor-due-diligence-software"),
    slug: "vendor-due-diligence-software",
    title: "Vendor Due Diligence Software",
    primaryKeyword: "vendor due diligence software",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-onboard-high-risk-vendors"), term("due-diligence")],
  },
  {
    tier: "solution",
    path: s("third-party-vendor-compliance"),
    slug: "third-party-vendor-compliance",
    title: "Third-Party Vendor Compliance",
    primaryKeyword: "third party vendor compliance",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [s("vendor-compliance-dashboard"), g("vendor-compliance-checklist")],
  },
  {
    tier: "solution",
    path: s("vendor-information-management"),
    slug: "vendor-information-management",
    title: "Vendor Information Management",
    primaryKeyword: "vendor information management",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [term("vendor-master-record"), VENDOR_HEAD_TOOL],
  },
  {
    tier: "solution",
    path: s("vendor-document-portal"),
    slug: "vendor-document-portal",
    title: "Vendor Document Portal",
    primaryKeyword: "vendor document portal",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [s("vendor-setup-portal"), s("vendor-document-collection")],
  },
  {
    tier: "solution",
    path: s("vendor-compliance-dashboard"),
    slug: "vendor-compliance-dashboard",
    title: "Vendor Compliance Dashboard",
    primaryKeyword: "vendor compliance dashboard",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), s("third-party-vendor-compliance")],
  },
  {
    tier: "solution",
    path: s("vendor-risk-tiering-software"),
    slug: "vendor-risk-tiering-software",
    title: "Vendor Risk Tiering Software",
    primaryKeyword: "vendor risk tiering software",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-set-vendor-document-requirements-by-tier"), term("vendor-tier")],
  },
  {
    tier: "solution",
    path: s("vendor-payment-hold-controls"),
    slug: "vendor-payment-hold-controls",
    title: "Vendor Payment Hold Controls",
    primaryKeyword: "vendor payment hold controls",
    difficulty: "hard",
    linkUp: [VENDOR_HUB, VENDOR_PRODUCT, VENDOR_HEAD_SOLUTION],
    linkSideways: [g("how-to-block-payments-for-non-compliant-vendors"), s("vendor-compliance-dashboard")],
  },
];
