import type { ColonyLink, ColonyPage } from "./types";

export const VENDOR_HUB = "/vendor-onboarding/";
export const VENDOR_PRODUCT = "/products/vendor-packet/";
export const VENDOR_HEAD_SOLUTION = "/solutions/vendor-packet-software/";
export const VENDOR_HEAD_TOOL = "/tools/vendor-information-form-template/";

export const s = (slug: string) => `/solutions/${slug}/`;
export const g = (slug: string) => `/guides/${slug}/`;
export const term = (slug: string) => `/glossary/${slug}/`;
export const industry = (industrySlug: string, workflowSlug: string) =>
  `/industries/${industrySlug}/${workflowSlug}/`;

export const VENDOR_HUB_COLONY_GUIDES: ColonyLink[] = [
  { label: "Vendor compliance checklist", href: g("vendor-compliance-checklist") },
  { label: "How to build a vendor onboarding checklist", href: g("how-to-build-a-vendor-onboarding-checklist") },
  { label: "What is a vendor packet?", href: g("what-is-a-vendor-packet") },
  { label: "How to send a vendor portal link", href: g("how-to-send-a-vendor-portal-link") },
  { label: "How to collect vendor documents in one place", href: g("how-to-collect-vendor-documents-in-one-place") },
  { label: "How to approve a new vendor", href: g("how-to-approve-a-new-vendor") },
  { label: "How to track vendor onboarding status", href: g("how-to-track-vendor-onboarding-status") },
  { label: "How to collect W-9 and COI together", href: g("how-to-collect-w9-and-coi-together") },
  { label: "How to export vendor onboarding evidence", href: g("how-to-export-vendor-onboarding-evidence") },
];

export const VENDOR_PAGES_BASE: ColonyPage[] = [
  {
    tier: "glossary",
    path: term("vendor-onboarding"),
    slug: "vendor-onboarding",
    title: "Vendor Onboarding",
    primaryKeyword: "vendor onboarding",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, g("how-to-build-a-vendor-onboarding-checklist")],
    linkSideways: [term("onboarding-packet"), term("vendor-packet")],
  },
  {
    tier: "glossary",
    path: term("onboarding-packet"),
    slug: "onboarding-packet",
    title: "Onboarding Packet",
    primaryKeyword: "onboarding packet",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, g("what-is-a-vendor-packet")],
    linkSideways: [term("vendor-packet"), term("vendor-onboarding")],
  },
  {
    tier: "glossary",
    path: term("vendor-packet"),
    slug: "vendor-packet",
    title: "Vendor Packet",
    primaryKeyword: "vendor packet",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, g("what-is-a-vendor-packet")],
    linkSideways: [term("onboarding-packet"), term("vendor-master-record")],
  },
  {
    tier: "glossary",
    path: term("vendor-tier"),
    slug: "vendor-tier",
    title: "Vendor Tier",
    primaryKeyword: "vendor tier",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, g("how-to-set-vendor-document-requirements-by-tier")],
    linkSideways: [term("due-diligence"), s("vendor-risk-tiering-software")],
  },
  {
    tier: "glossary",
    path: term("vendor-master-record"),
    slug: "vendor-master-record",
    title: "Vendor Master Record",
    primaryKeyword: "vendor master record",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [term("vendor-packet"), g("how-to-integrate-vendor-onboarding-with-ap")],
  },
  {
    tier: "glossary",
    path: term("vendor-offboarding"),
    slug: "vendor-offboarding",
    title: "Vendor Offboarding",
    primaryKeyword: "vendor offboarding",
    difficulty: "medium",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, term("vendor-master-record")],
    linkSideways: [term("vendor-packet"), term("vendor-onboarding")],
  },
  {
    tier: "glossary",
    path: term("due-diligence"),
    slug: "due-diligence",
    title: "Due Diligence",
    primaryKeyword: "vendor due diligence",
    difficulty: "easy",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, g("how-to-onboard-high-risk-vendors")],
    linkSideways: [term("vendor-tier"), s("vendor-due-diligence-software")],
  },
  {
    tier: "glossary",
    path: term("beneficial-ownership"),
    slug: "beneficial-ownership",
    title: "Beneficial Ownership",
    primaryKeyword: "beneficial ownership",
    difficulty: "medium",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, g("how-to-onboard-high-risk-vendors")],
    linkSideways: [term("due-diligence"), term("vendor-tier")],
  },
  {
    tier: "guide",
    path: g("vendor-compliance-checklist"),
    slug: "vendor-compliance-checklist",
    title: "Vendor Compliance Checklist",
    primaryKeyword: "vendor compliance checklist",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), g("what-is-a-vendor-packet")],
  },
  {
    tier: "guide",
    path: g("how-to-build-a-vendor-onboarding-checklist"),
    slug: "how-to-build-a-vendor-onboarding-checklist",
    title: "How to Build a Vendor Onboarding Checklist",
    primaryKeyword: "vendor onboarding checklist",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("vendor-compliance-checklist"), g("how-to-set-vendor-document-requirements-by-tier")],
  },
  {
    tier: "guide",
    path: g("what-is-a-vendor-packet"),
    slug: "what-is-a-vendor-packet",
    title: "What Is a Vendor Packet?",
    primaryKeyword: "vendor packet",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, term("vendor-packet")],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), g("how-to-handle-incomplete-vendor-packets")],
  },
  {
    tier: "guide",
    path: g("how-to-send-a-vendor-portal-link"),
    slug: "how-to-send-a-vendor-portal-link",
    title: "How to Send a Vendor Portal Link",
    primaryKeyword: "vendor portal link",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("how-to-collect-vendor-documents-in-one-place"), s("vendor-setup-portal")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-vendor-documents-in-one-place"),
    slug: "how-to-collect-vendor-documents-in-one-place",
    title: "How to Collect Vendor Documents in One Place",
    primaryKeyword: "collect vendor documents",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("how-to-send-a-vendor-portal-link"), s("vendor-document-collection")],
  },
  {
    tier: "guide",
    path: g("how-to-approve-a-new-vendor"),
    slug: "how-to-approve-a-new-vendor",
    title: "How to Approve a New Vendor",
    primaryKeyword: "new vendor approval",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), g("how-to-block-payments-for-non-compliant-vendors")],
  },
  {
    tier: "guide",
    path: g("how-to-track-vendor-onboarding-status"),
    slug: "how-to-track-vendor-onboarding-status",
    title: "How to Track Vendor Onboarding Status",
    primaryKeyword: "vendor onboarding status",
    difficulty: "easy",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("how-to-approve-a-new-vendor"), s("vendor-compliance-dashboard")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-w9-and-coi-together"),
    slug: "how-to-collect-w9-and-coi-together",
    title: "How to Collect W-9 and COI Together",
    primaryKeyword: "collect w9 and coi together",
    difficulty: "medium",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("what-is-a-vendor-packet"), g("how-to-collect-vendor-documents-in-one-place")],
  },
];
