import type { ColonyPage } from "./types";
import { VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT, g, industry, s, term } from "./vendor";

export const VENDOR_PAGES_EXTRA: ColonyPage[] = [
  {
    tier: "guide",
    path: g("how-to-export-vendor-onboarding-evidence"),
    slug: "how-to-export-vendor-onboarding-evidence",
    title: "How to Export Vendor Onboarding Evidence",
    primaryKeyword: "export vendor onboarding evidence",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-approve-a-new-vendor"), g("vendor-compliance-checklist")],
  },
  {
    tier: "guide",
    path: g("how-to-set-vendor-document-requirements-by-tier"),
    slug: "how-to-set-vendor-document-requirements-by-tier",
    title: "How to Set Vendor Document Requirements by Tier",
    primaryKeyword: "vendor document requirements by tier",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, term("vendor-tier")],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("vendor-risk-tiering-software")],
  },
  {
    tier: "guide",
    path: g("how-to-handle-incomplete-vendor-packets"),
    slug: "how-to-handle-incomplete-vendor-packets",
    title: "How to Handle Incomplete Vendor Packets",
    primaryKeyword: "incomplete vendor packet",
    difficulty: "medium",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, g("what-is-a-vendor-packet")],
    linkSideways: [g("how-to-track-vendor-onboarding-status"), g("how-to-block-payments-for-non-compliant-vendors")],
  },
  {
    tier: "guide",
    path: g("how-to-onboard-high-risk-vendors"),
    slug: "how-to-onboard-high-risk-vendors",
    title: "How to Onboard High-Risk Vendors",
    primaryKeyword: "high risk vendor onboarding",
    difficulty: "hard",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, term("due-diligence")],
    linkSideways: [g("how-to-set-vendor-document-requirements-by-tier"), s("vendor-due-diligence-software")],
  },
  {
    tier: "guide",
    path: g("how-to-block-payments-for-non-compliant-vendors"),
    slug: "how-to-block-payments-for-non-compliant-vendors",
    title: "How to Block Payments for Non-Compliant Vendors",
    primaryKeyword: "block payments non compliant vendors",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_PRODUCT, VENDOR_HEAD_SOLUTION],
    linkSideways: [g("how-to-approve-a-new-vendor"), s("vendor-payment-hold-controls")],
  },
  {
    tier: "guide",
    path: g("how-to-reduce-vendor-onboarding-time"),
    slug: "how-to-reduce-vendor-onboarding-time",
    title: "How to Reduce Vendor Onboarding Time",
    primaryKeyword: "reduce vendor onboarding time",
    difficulty: "medium",
    linkUp: [VENDOR_HEAD_SOLUTION, VENDOR_HUB, VENDOR_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("supplier-onboarding-workflow")],
  },
  {
    tier: "guide",
    path: g("how-to-re-onboard-vendors-after-merger"),
    slug: "how-to-re-onboard-vendors-after-merger",
    title: "How to Re-Onboard Vendors After Merger",
    primaryKeyword: "re-onboard vendors after merger",
    difficulty: "hard",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-integrate-vendor-onboarding-with-ap"), term("vendor-master-record")],
  },
  {
    tier: "guide",
    path: g("how-to-integrate-vendor-onboarding-with-ap"),
    slug: "how-to-integrate-vendor-onboarding-with-ap",
    title: "How to Integrate Vendor Onboarding with AP",
    primaryKeyword: "integrate vendor onboarding ap",
    difficulty: "hard",
    linkUp: [VENDOR_HUB, VENDOR_PRODUCT, VENDOR_HEAD_SOLUTION],
    linkSideways: [g("how-to-block-payments-for-non-compliant-vendors"), term("vendor-master-record")],
  },
  {
    tier: "industry",
    path: industry("construction", "build-vendor-onboarding-packets"),
    slug: "construction-build-vendor-onboarding-packets",
    title: "Build Vendor Onboarding Packets for Construction",
    primaryKeyword: "construction vendor onboarding",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-collect-w9-and-coi-together"), g("how-to-collect-vendor-documents-in-one-place")],
  },
  {
    tier: "industry",
    path: industry("staffing", "build-vendor-onboarding-packets"),
    slug: "staffing-build-vendor-onboarding-packets",
    title: "Build Vendor Onboarding Packets for Staffing",
    primaryKeyword: "staffing vendor onboarding",
    difficulty: "medium",
    linkUp: [VENDOR_HUB, VENDOR_HEAD_SOLUTION, VENDOR_PRODUCT],
    linkSideways: [g("how-to-build-a-vendor-onboarding-checklist"), s("supplier-onboarding-workflow")],
  },
];
