import type { ColonyPage } from "./types";
import { W9_HEAD_SOLUTION, W9_HEAD_TOOL, W9_HUB, W9_PRODUCT } from "./w9";

const s = (slug: string) => `/solutions/${slug}/`;
const g = (slug: string) => `/guides/${slug}/`;
const term = (slug: string) => `/glossary/${slug}/`;

export const W9_PAGES_SOLUTIONS: ColonyPage[] = [
  {
    tier: "solution",
    path: W9_HEAD_SOLUTION,
    slug: "w9-request-from-vendor",
    title: "Request W-9 from Vendor",
    primaryKeyword: "w9 request from vendor",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_PRODUCT],
    linkSideways: [s("collect-w9-online"), s("w9-reminder-automation")],
  },
  {
    tier: "solution",
    path: s("collect-w9-online"),
    slug: "collect-w9-online",
    title: "Collect W-9 Online",
    primaryKeyword: "collect w9 online",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("w9-collection-software"), g("how-to-collect-w9s-from-vendors")],
  },
  {
    tier: "solution",
    path: s("bulk-w9-request"),
    slug: "bulk-w9-request",
    title: "Bulk W-9 Request",
    primaryKeyword: "bulk w9 request software",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("w9-bulk-collection-software"), g("how-to-bulk-request-w9s-from-vendors")],
  },
  {
    tier: "solution",
    path: s("w9-reminder-automation"),
    slug: "w9-reminder-automation",
    title: "W-9 Reminder Automation",
    primaryKeyword: "w9 reminder automation",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("collect-w9-online"), g("how-to-send-a-w9-request-email")],
  },
  {
    tier: "solution",
    path: s("stale-w9-alerts"),
    slug: "stale-w9-alerts",
    title: "Stale W-9 Alerts",
    primaryKeyword: "stale w9 alerts",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [g("how-to-re-collect-stale-w-9s"), s("w9-year-end-audit-packet")],
  },
  {
    tier: "solution",
    path: s("w9-validation-before-payment"),
    slug: "w9-validation-before-payment",
    title: "W-9 Validation Before Payment",
    primaryKeyword: "w9 validation before payment",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [g("how-to-collect-w9s-before-first-payment"), term("tin-validation")],
  },
  {
    tier: "solution",
    path: s("w9-collection-software"),
    slug: "w9-collection-software",
    title: "W-9 Collection Software",
    primaryKeyword: "w9 collection software",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("collect-w9-online"), s("vendor-w9-management")],
  },
  {
    tier: "solution",
    path: s("w9-bulk-collection-software"),
    slug: "w9-bulk-collection-software",
    title: "W-9 Bulk Collection Software",
    primaryKeyword: "w9 bulk collection software",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("bulk-w9-request"), g("how-to-bulk-request-w9s-from-vendors")],
  },
  {
    tier: "solution",
    path: s("w9-backup-withholding-controls"),
    slug: "w9-backup-withholding-controls",
    title: "W-9 Backup Withholding Controls",
    primaryKeyword: "w9 backup withholding controls",
    difficulty: "hard",
    linkUp: [W9_HUB, W9_PRODUCT, W9_HEAD_SOLUTION],
    linkSideways: [g("what-is-backup-withholding-and-how-to-avoid-it"), term("backup-withholding")],
  },
  {
    tier: "solution",
    path: s("w9-year-end-audit-packet"),
    slug: "w9-year-end-audit-packet",
    title: "W-9 Year-End Audit Packet",
    primaryKeyword: "w9 year end audit packet",
    difficulty: "hard",
    linkUp: [W9_HUB, W9_PRODUCT, W9_HEAD_SOLUTION],
    linkSideways: [g("how-to-prepare-for-1099-filing-season"), s("stale-w9-alerts")],
  },
  {
    tier: "solution",
    path: s("w9-llc-classification-check"),
    slug: "w9-llc-classification-check",
    title: "W-9 LLC Classification Check",
    primaryKeyword: "w9 llc classification check",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [g("how-to-handle-w9-for-llc-vendors"), s("w9-validation-before-payment")],
  },
  {
    tier: "solution",
    path: s("vendor-w9-management"),
    slug: "vendor-w9-management",
    title: "Vendor W-9 Management",
    primaryKeyword: "vendor w9 management",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [s("w9-collection-software"), g("how-to-collect-w9s-from-vendors")],
  },
];
