import type { ColonyLink, ColonyPage } from "./types";

export const W9_HUB = "/w9-collection/";
export const W9_PRODUCT = "/products/w9-collector/";
export const W9_HEAD_SOLUTION = "/solutions/w9-request-from-vendor/";
export const W9_HEAD_TOOL = "/tools/w9-request-generator/";

const s = (slug: string) => `/solutions/${slug}/`;
const g = (slug: string) => `/guides/${slug}/`;
const term = (slug: string) => `/glossary/${slug}/`;

export const W9_HUB_COLONY_GUIDES: ColonyLink[] = [
  { label: "How to collect W-9s from vendors", href: g("how-to-collect-w9s-from-vendors") },
  { label: "How to request a W-9 from a new vendor", href: g("how-to-request-a-w-9-from-a-new-vendor") },
  { label: "How to send a W-9 request email", href: g("how-to-send-a-w9-request-email") },
  { label: "What is IRS Form W-9?", href: g("what-is-irs-form-w9") },
  { label: "How to validate a vendor TIN", href: g("how-to-validate-a-vendor-tin") },
  { label: "How to re-collect stale W-9s", href: g("how-to-re-collect-stale-w-9s") },
  { label: "How to bulk request W-9s from vendors", href: g("how-to-bulk-request-w9s-from-vendors") },
  { label: "How to prepare for 1099 filing season", href: g("how-to-prepare-for-1099-filing-season") },
  { label: "How to handle a missing W-9 at year-end", href: g("how-to-handle-a-missing-w-9-at-year-end") },
];

export const W9_PAGES_BASE: ColonyPage[] = [
  {
    tier: "glossary",
    path: term("w-9"),
    slug: "w-9",
    title: "W-9",
    primaryKeyword: "form w-9",
    difficulty: "easy",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, g("what-is-irs-form-w9")],
    linkSideways: [term("taxpayer-identification-number"), term("tin-validation")],
  },
  {
    tier: "glossary",
    path: term("tin-matching"),
    slug: "tin-matching",
    title: "TIN Matching",
    primaryKeyword: "tin matching",
    difficulty: "easy",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, g("how-to-validate-a-vendor-tin")],
    linkSideways: [term("tin-validation"), term("payee-name-mismatch")],
  },
  {
    tier: "glossary",
    path: term("backup-withholding"),
    slug: "backup-withholding",
    title: "Backup Withholding",
    primaryKeyword: "backup withholding",
    difficulty: "easy",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, g("what-is-backup-withholding-and-how-to-avoid-it")],
    linkSideways: [term("exempt-payee-code"), term("tin-validation")],
  },
  {
    tier: "glossary",
    path: term("1099-nec"),
    slug: "1099-nec",
    title: "1099-NEC",
    primaryKeyword: "1099 nec",
    difficulty: "easy",
    linkUp: [W9_HUB, g("when-to-issue-a-1099-to-a-vendor"), W9_HEAD_SOLUTION],
    linkSideways: [term("w-9"), g("how-to-prepare-for-1099-filing-season")],
  },
  {
    tier: "glossary",
    path: term("taxpayer-identification-number"),
    slug: "taxpayer-identification-number",
    title: "Taxpayer Identification Number",
    primaryKeyword: "taxpayer identification number",
    difficulty: "easy",
    linkUp: [W9_HUB, term("w-9"), g("how-to-validate-a-vendor-tin")],
    linkSideways: [term("tin-matching"), term("tin-validation")],
  },
  {
    tier: "glossary",
    path: term("tin-validation"),
    slug: "tin-validation",
    title: "TIN Validation",
    primaryKeyword: "tin validation",
    difficulty: "easy",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [term("tin-matching"), g("how-to-validate-a-vendor-tin")],
  },
  {
    tier: "glossary",
    path: term("exempt-payee-code"),
    slug: "exempt-payee-code",
    title: "Exempt Payee Code",
    primaryKeyword: "exempt payee code",
    difficulty: "medium",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, term("backup-withholding")],
    linkSideways: [term("w-9"), s("w9-backup-withholding-controls")],
  },
  {
    tier: "glossary",
    path: term("payee-name-mismatch"),
    slug: "payee-name-mismatch",
    title: "Payee Name Mismatch",
    primaryKeyword: "payee name mismatch",
    difficulty: "medium",
    linkUp: [W9_HEAD_SOLUTION, g("how-to-fix-a-tin-mismatch-on-a-w9"), W9_HUB],
    linkSideways: [term("tin-matching"), g("how-to-validate-a-vendor-tin")],
  },
  {
    tier: "guide",
    path: g("how-to-collect-w9s-from-vendors"),
    slug: "how-to-collect-w9s-from-vendors",
    title: "How to Collect W-9s from Vendors",
    primaryKeyword: "collect w9 from vendors",
    difficulty: "easy",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, W9_PRODUCT],
    linkSideways: [g("how-to-request-a-w-9-from-a-new-vendor"), g("how-to-send-a-w9-request-email")],
  },
  {
    tier: "guide",
    path: g("how-to-request-a-w-9-from-a-new-vendor"),
    slug: "how-to-request-a-w-9-from-a-new-vendor",
    title: "How to Request a W-9 from a New Vendor",
    primaryKeyword: "request w9 from new vendor",
    difficulty: "easy",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, W9_PRODUCT],
    linkSideways: [g("how-to-collect-w9s-from-vendors"), g("how-to-collect-w9s-before-first-payment")],
  },
  {
    tier: "guide",
    path: g("how-to-send-a-w9-request-email"),
    slug: "how-to-send-a-w9-request-email",
    title: "How to Send a W-9 Request Email",
    primaryKeyword: "w9 request email",
    difficulty: "easy",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, W9_HEAD_TOOL],
    linkSideways: [g("how-to-request-a-w-9-from-a-new-vendor"), g("how-to-bulk-request-w9s-from-vendors")],
  },
  {
    tier: "guide",
    path: g("what-is-irs-form-w9"),
    slug: "what-is-irs-form-w9",
    title: "What Is IRS Form W-9?",
    primaryKeyword: "irs form w9",
    difficulty: "easy",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, term("w-9")],
    linkSideways: [g("how-to-collect-w9s-from-vendors"), g("w9-vs-w8-which-form")],
  },
  {
    tier: "guide",
    path: g("how-to-validate-a-vendor-tin"),
    slug: "how-to-validate-a-vendor-tin",
    title: "How to Validate a Vendor TIN",
    primaryKeyword: "validate vendor tin",
    difficulty: "medium",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, W9_PRODUCT],
    linkSideways: [g("how-to-fix-a-tin-mismatch-on-a-w9"), term("tin-matching")],
  },
  {
    tier: "guide",
    path: g("how-to-re-collect-stale-w-9s"),
    slug: "how-to-re-collect-stale-w-9s",
    title: "How to Re-collect Stale W-9s",
    primaryKeyword: "re-collect stale w9",
    difficulty: "medium",
    linkUp: [W9_HUB, W9_HEAD_SOLUTION, W9_PRODUCT],
    linkSideways: [g("how-to-bulk-request-w9s-from-vendors"), s("stale-w9-alerts")],
  },
  {
    tier: "guide",
    path: g("how-to-bulk-request-w9s-from-vendors"),
    slug: "how-to-bulk-request-w9s-from-vendors",
    title: "How to Bulk Request W-9s from Vendors",
    primaryKeyword: "bulk w9 request",
    difficulty: "medium",
    linkUp: [W9_HEAD_SOLUTION, W9_HUB, W9_PRODUCT],
    linkSideways: [g("how-to-send-a-w9-request-email"), s("bulk-w9-request")],
  },
];
